### ISSUE TITLE
18Ardennes: cannot par a major in 2nd tranche

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#112]
Player 4 has won the bid on the P, but in the SR (when trying to par) I get an error message "cannot buy a share of P". There was a competitive auction. The previous tranche worked fine.

**Comment by ollybh** [comment]
This error is because Player 4 is at certificate limit, and so cannot buy the shares needed to start P.

There are two parts needed to fix this:

1. Player 4 shouldn't be at limit. The limit is six certs, they have 80% of E (three certs) and minors 7 and 5 (one cert each). The sixth certificate is from the hidden concession company that they got in the major auction – this shouldn't count as a certificate.
2. The par buttons should be shown if some really is at certificate limit. The only options given should be to sell shares.

**Comment by ollybh** [comment]
@ianwilson156 Good catch, BTW.

**Comment by ollybh** [comment]
Rules lawyer time: starting a major company increases your certificate count by one (you gain the president's 40% share certificate, plus one 20% share certificate in exchange for the minor). Would it be possible to get in a situation where you are at limit, do not have any shares that can be sold (all president's certificates?) and have won an auction? You wouldn't be able to fulfil the obligation to start the major, so would be bankrupted.

**Comment by ianwilson156** [comment]
a) Not really - it just happened.
b) I've never seen it happen, since you generally have at least 30% in each company and therefore can sell one. But yes, in the situation you describe you would be in deep trouble... I've just checked the rule, it does indeed say bankrupt.

**Comment by ollybh** [comment]
Fixed in commits b0114bd0d and 5676ea529.
I've added a note to issue #111 about checking that the player has space for the extra certificate (or can sell) before allowing them to bid for a major.
