### ISSUE TITLE
Colours don't work with #8 and #9 (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#123]
The coloured background works ok except for minors 8 & 9 (in Paris)...

**Comment by ollybh** [comment]
Paris is working now. It had to be handled slightly differently because of the different public companies in the east and west cities, and I didn't have time to do this last night.
I'm more mystified as to why Charleroi isn't getting a coloured token. That one shouldn't be different to other cities...

**Comment by ollybh** [comment]
That was because tokening Charleroi involves replacing the mine token, obviously. This (and port tokens) should now be working.
