### ISSUE TITLE
18CH - extra slot appears in Zurich

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#142]
Hotseat game, when AB upgrades Zurich to green an extra slot appears with 'NB' in it. And when NB closes during AB's turn, the slot stays there.

**Comment by ollybh** [comment]
This is a bit strange. AB has acquired the NB private and taken its token in Zürich, but the NB reservation still seems to be hanging around. So when the tile is upgraded to green, an extra slot is created for this reservation.

**Comment by ollybh** [comment]
![image](https://github.com/ollybh/18xx/assets/11144854/d43d37e5-3ff9-40fd-ad46-0c9684884713)

**Comment by ollybh** [comment]
This was the same problem as seen in tobymao#10442. The fix in tobymao#10443 was incomplete, it only covered the case where the token had been taken when a public company was first formed. This time the token had been taken after exchanging a private railway company for a share in an existing public company.

Fixed in commit 98eef5117.
