### ISSUE TITLE
Stubs in private company home hexes should be removed when the company is exchanged or closes

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#30]
OR6.1: RP wants to build in hex F13 (CM&P has closed) but - even though it is highlighted - nothing happens when one clicks on the hex. E12 is ok.
Looks like that - when CM&P closed - this hex wasn't freed up.

**Comment by ianwilson156** [comment]
This was after upgrading E14. If instead RP builds E12 it works. Looks like it is still insisting to follow the privates restrictions.

**Comment by ollybh** [comment]
This is something I've not implemented yet: the right to build on the private home hexes is released once the private company closes, but the requirement to follow the route of the private railway is still in force. So that game is trying to enforce a tile in F13 that has NW and NE exits, so you didn't have a route that let you lay the tile that satisfied those requirements.

I need to remove these permanent restrictions on yellow tiles in private home hexes and redo them as abilities that disappear when the private is exchanged or closes.

**Comment by ianwilson156** [comment]
Ah, that explains it. So not really a bug, more a feature not yet implemented.

**Comment by ollybh** [comment]
Stubs are now implemented using abilities, and go away when the private company is exchanged for a share. Fixed in commits 59f3c3bf7a and 4b42ba4654.

**Comment by ianwilson156** [comment]
Thanks, this seems to work fine now.
Just one comment: stubs of an unsold private don't disappear (even though the private is no longer available) after the 5E/4M is bought.
I guess this will be part of the Final Closure Round (which hasn't been implemented yet).
