### ISSUE TITLE
1858: cannot review finished game

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#31]
When trying to review my latest game, I get the following message:

"We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 355
Broken action: { "type": "pass", "entity": "ZPB", "entity_type": "corporation", "id": 355, "created_at": 1668274116 }"

This is when ZPB is running during OR4.1 - this was ok when I played the game originally!

**Comment by ollybh** [comment]
Can you try opening this game again, and see if it works now? I fixed a couple of code issues that might have been causing weird things like this.

If it still gives an error, can you please send me the JSON export?

**Comment by ianwilson156** [comment]
Still no good - JSON sent in email.

**Comment by ollybh** [comment]
This was caused by the changes to the tokening step I made when fixing issue #1: in OR4.2 ZPB didn't have any routes to open city spots, so the changed code was automatically skipping the token step. When you had played the game this check wasn't being made, so ZPB had had to pass that action. This pass action was causing the error when the game was being reloaded, as it looked like it was for the next step, run routes, which can't be passed.
