### ISSUE TITLE
18Ardennes: all corps available at 2nd auction

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#95]
When we get to the 2nd auction of majors, all 6 corporations are available, not just the 2 which should be left.

**Comment by ollybh** [comment]
Thanks for catching this one. It is fixed in commit cca2994c8.

If you're doing more testing, you'll notice that for SR3 (and later) there are no checks for consent if you try and exchange a minor for a share in a major that has already operated – I haven't implement this yet (it won't take long, I can reuse the code from 1858). If there's anything else wrong with the stock rounds, then it's something I've messed up or forgotten, so please let me know.
